apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-to-otel-collector
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: otel-demo
      podSelector:
        matchLabels:
          app.kubernetes.io/name: opentelemetry-collector
          app.kubernetes.io/instance: opentelemetry-demo
          component: agent-collector
    ports:
    - protocol: TCP
      port: 4317
    - protocol: TCP
      port: 4318